# Generated by Django 5.0.6 on 2026-03-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='is_suspended_by_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
