# Generated by Django 5.0.6 on 2026-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
