# Generated by Django 5.0.6 on 2026-03-22 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='access_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
