# Generated by Django 5.0.6 on 2026-03-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_payment_access_code_payment_gateway_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='flutterwave_tx_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='flutterwave_tx_ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(default='flutterwave', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
