# Generated by Django 5.0.6 on 2026-03-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_payment_currency_payment_flutterwave_tx_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(default='paystack', max_length=50),
        ),
    ]
